### ISSUE TITLE
clangd提示报错。  system：wsl2     neovim 0.10 

### ISSUE THREAD

**Issue by Learner-Geek-Perfectionist** [Kicamon/nvim#3]
![image](https://github.com/Kicamon/nvim/assets/48880596/2105aab8-e1e8-453a-ac5c-c08984c9faa9)

**Comment by Learner-Geek-Perfectionist** [comment]
您的配置不会自动安装clangd服务器吗？如果本地没用clangd服务器。

**Comment by Kicamon** [comment]
不会wwww，mason插件可以，但是我不用hhh

**Comment by Kicamon** [comment]
自己手动安装一下吧

**Comment by Kicamon** [comment]
你要用的话把readme文件里Install这一部分列出来的都安装一下

**Comment by Learner-Geek-Perfectionist** [comment]
行吧，up也是acmer，应该也写c++把。

**Comment by Kicamon** [comment]
写的
