### ISSUE TITLE
请问如何在我自己的Neovim配置中使用`markdown.lua`？

### ISSUE THREAD

**Issue by PILIHU2022** [Kicamon/nvim#4]
我已经在我的Neovim配置中的`core`文件夹中添加了`keymap_Script.lua`，并且在`keymap`文件夹中的`markdown.lua`正确地require了。但是并没有生效，请问应该如何写才能正确地解决问题？

`init.lua`中也require了`keymap_Script.lua`，但是并不能使用
[仓库](https://github.com/PILIHU2022/My-dotfiles/tree/test/.config/nvim-use-cmp)

**Comment by Kicamon** [comment]
你没有require markdown.lua吧。你看看[调用markdown keymap](https://github.com/Kicamon/nvim/blob/main/lua/internal/event.lua#L79)

**Comment by PILIHU2022** [comment]
解决了，这个require藏的太深了💦，感谢
